var a = 3;
var b = 4;
var c = 2;
console.log("I predict a < b true");
console.log(a < b);
console.log("I predict c < b true ");
console.log(c < b);
console.log("c=b false");
console.log(c == b);
console.log("I predict b > c true");
console.log(b > c);
console.log("I predict a !== c true");
console.log(a !== c);
console.log("I predict a == b false");
console.log(a == b);
console.log("I predict c < a true");
console.log(c < a);
console.log("I predict b !== c true");
console.log(b !== c);
console.log("I predict c==b false");
console.log(c == b);
console.log("I prdeict a+c > b true");
console.log(a + c > b);
console.log("I predict b-c < a true");
console.log(b - c < a);
console.log("I predictb+c< a false");
console.log(b + c < a);
console.log("I predict a-c> b false");
console.log(a - c > b);
console.log("I prdict b===c false");
console.log(b === c);
